# Generated by Django 5.0.7 on 2024-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(max_length=155, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='students',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='Хобби'),
        ),
    ]
